### ISSUE TITLE
Cannot unzip the train_dataset

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#12]
Hi,

I've successfully downloaded validation and test data.
I've also download first 5 sets of train dataset from huggingface, however I cannot open the file, even with 7zip.
Can someone tell me in detail how I should access the dataset?

Thank you in advance,

**Comment by piperwolters** [comment]
Hi, thank you for your interest in this project.

For the files from huggingface, you have to first cat all of the .7z.001, .7z.002, ... files into a single .7z file.
`cat train_urban_set.7z.001 train_urban_set.7z.002 ... > train_urban_set.7z`

Then you can use 7zip to unzip.
`7z x train_urban_set.7z`

**Comment by yunseok624** [comment]
> Hi, thank you for your interest in this project.
> 
> For the files from huggingface, you have to first cat all of the .7z.001, .7z.002, ... files into a single .7z file. `cat train_urban_set.7z.001 train_urban_set.7z.002 ... > train_urban_set.7z`
> 
> Then you can use 7zip to unzip. `7z x train_urban_set.7z`

Do I have to donwload all .7z file? Is it okay to download the first 5 (I don't have enouogh space to keep them all)?
Also how do I cat those files?

**Comment by piperwolters** [comment]
You do not need to download all of them. Just cat the files that you have downloaded.
If you are using linux, [here](https://phoenixnap.com/kb/linux-cat-command) is an article explaining what the `cat` command is doing.

**Comment by piperwolters** [comment]
Ah, I am mistaken - you do need all of the .7z files to be able to unzip. The ideal workflow would be to download all .7z files, and then run `7z x archive.7z.001 -o destination_directory` which will automatically detect and unzip the other parts.

If you do not have enough room to keep all of them, this will be difficult. I can work on uploading a much smaller dataset, but cannot guarantee that a dataset that small will lead to successful super-resolution.

**Comment by piperwolters** [comment]
Of course, the whole urban training set is 939GB.

**Comment by yunseok624** [comment]
that's the size of unziped urban dataset, am I correct?
Also what is the size of the train_full_set?
