### ISSUE TITLE
About logging

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#16]
Hi,

Sorry for making issues with stupid questions.
I just don't know where I should ask. If I want to log the process then what should I write in "project" and "resume id"? I already have made an account in wandb, but don't know what to do with them.
![image](https://github.com/allenai/satlas-super-resolution/assets/58263915/f90b3dc7-05e5-4a69-a63e-54deda2a1eee)

Thank you in advance.

**Comment by piperwolters** [comment]
No worries at all! Keep asking and I will respond as soon as I am able. 

The project should be the wandb project (you might have to make one). Here is what my wandb project name looks like, in the upper righthand corner. You do not need to see resume_id.
![Screen Shot 2024-03-20 at 9 40 42 AM](https://github.com/allenai/satlas-super-resolution/assets/46272042/0f3fb249-e72b-45e8-b06f-5465b9f15799)

**Comment by yunseok624** [comment]
So If my project name is MISR then I just write:
project: MISR ?

**Comment by piperwolters** [comment]
Hello, yes that should work. What do you mean by API code?

**Comment by yunseok624** [comment]
Solved the problem.
Thanks
