### ISSUE TITLE
Data Normalization in Sentinel-2

### ISSUE THREAD

**Issue by csaybar** [allenai/satlas-super-resolution#2]
Hi!,

First off, thank you so much for your effort in sharing the weights and code for SR (not many people in the field tend to do that)! Unfortunately, I am having some issues reproducing the results.

If I intend to apply the model in a fresh Sentinel-2 scene:

a) Should I use L1C or L2A data? If it's L2A, are you using Sen2Cor processing? In the https://satlas.allen.ai/map also seems like you applied a blur kernel to the Sentinel-2.

b) Did you apply any form of data normalization when converting the S2 data to .png?

Thank you very much!

https://satlas.allen.ai/map?state={%22view%22:{%22longitude%22:-113.30307090140528,%22latitude%22:44.503575173782934,%22zoom%22:14.606271409299431,%22pitch%22:0,%22bearing%22:0},%22showHeatmap%22:true,%22showAnimation%22:false,%22showSatellite%22:false,%22selectedDateOption%22:%222022-12%22,%22selectedDateOptionSecondary%22:%222016-01%22,%22selectedStartDateOption%22:%222016-01%22,%22selectedEndDateOption%22:%222022-12%22,%22selectedTreeCoverFill%22:[{%22label%22:%22None%22,%22isChecked%22:false},{%22label%22:%22Low%22,%22isChecked%22:false},{%22label%22:%22Medium%22,%22isChecked%22:true},{%22label%22:%22High%22,%22isChecked%22:true},{%22label%22:%22Full%22,%22isChecked%22:true}],%22selectedMarineInfra%22:[{%22label%22:%22Offshore%20Wind%20Turbines%22,%22isChecked%22:true},{%22label%22:%22Offshore%20Platforms%22,%22isChecked%22:false}],%22selectedRenewableEnergy%22:[{%22label%22:%22Solar%20Farms%22,%22isChecked%22:true},{%22label%22:%22Onshore%20Wind%20Turbines%22,%22isChecked%22:true}],%22selectedApplication%22:%22Super%20Resolution%22,%22selectedLayout%22:%22Single%20Map%22}

![image](https://github.com/allenai/satlas-super-resolution/assets/16768318/0621d424-9950-429b-a691-bb3e991e74de)

**Comment by csaybar** [comment]
I prepared a reproducible demo in colab: https://colab.research.google.com/drive/1OlrYome8gcBH6Wu3SQhaw6mSlr2apWdV?usp=sharing

Hope it helps!

**Comment by pbeukema** [comment]
Hi @csaybar, 
The main researcher of this work, @piperwolters, is on vacation this week but will get back to you asap.
Thanks!

**Comment by piperwolters** [comment]
> Hi!,
> 
> First off, thank you so much for your effort in sharing the weights and code for SR (not many people in the field tend to do that)! Unfortunately, I am having some issues reproducing the results.
> 
> If I intend to apply the model in a fresh Sentinel-2 scene:
> 
> a) Should I use L1C or L2A data? If it's L2A, are you using Sen2Cor processing? In the https://satlas.allen.ai/map also seems like you applied a blur kernel to the Sentinel-2.
> 
> b) Did you apply any form of data normalization when converting the S2 data to .png?
> 
> Thank you very much!
> 
> [https://satlas.allen.ai/map?state={%22view%22:{%22longitude%22:-113.30307090140528,%22latitude%22:44.503575173782934,%22zoom%22:14.606271409299431,%22pitch%22:0,%22bearing%22:0},%22showHeatmap%22:true,%22showAnimation%22:false,%22showSatellite%22:false,%22selectedDateOption%22:%222022-12%22,%22selectedDateOptionSecondary%22:%222016-01%22,%22selectedStartDateOption%22:%222016-01%22,%22selectedEndDateOption%22:%222022-12%22,%22selectedTreeCoverFill%22:[{%22label%22:%22None%22,%22isChecked%22:false},{%22label%22:%22Low%22,%22isChecked%22:false},{%22label%22:%22Medium%22,%22isChecked%22:true},{%22label%22:%22High%22,%22isChecked%22:true},{%22label%22:%22Full%22,%22isChecked%22:true}],%22selectedMarineInfra%22:[{%22label%22:%22Offshore%20Wind%20Turbines%22,%22isChecked%22:true},{%22label%22:%22Offshore%20Platforms%22,%22isChecked%22:false}],%22selectedRenewableEnergy%22:[{%22label%22:%22Solar%20Farms%22,%22isChecked%22:true},{%22label%22:%22Onshore%20Wind%20Turbines%22,%22isChecked%22:true}],%22selectedApplication%22:%22Super%20Resolution%22,%22selectedLayout%22:%22Single%20Map%22}](https://satlas.allen.ai/map?state=%7B%22view%22:%7B%22longitude%22:-113.30307090140528,%22latitude%22:44.503575173782934,%22zoom%22:14.606271409299431,%22pitch%22:0,%22bearing%22:0%7D,%22showHeatmap%22:true,%22showAnimation%22:false,%22showSatellite%22:false,%22selectedDateOption%22:%222022-12%22,%22selectedDateOptionSecondary%22:%222016-01%22,%22selectedStartDateOption%22:%222016-01%22,%22selectedEndDateOption%22:%222022-12%22,%22selectedTreeCoverFill%22:%5B%7B%22label%22:%22None%22,%22isChecked%22:false%7D,%7B%22label%22:%22Low%22,%22isChecked%22:false%7D,%7B%22label%22:%22Medium%22,%22isChecked%22:true%7D,%7B%22label%22:%22High%22,%22isChecked%22:true%7D,%7B%22label%22:%22Full%22,%22isChecked%22:true%7D%5D,%22selectedMarineInfra%22:%5B%7B%22label%22:%22Offshore%20Wind%20Turbines%22,%22isChecked%22:true%7D,%7B%22label%22:%22Offshore%20Platforms%22,%22isChecked%22:false%7D%5D,%22selectedRenewableEnergy%22:%5B%7B%22label%22:%22Solar%20Farms%22,%22isChecked%22:true%7D,%7B%22label%22:%22Onshore%20Wind%20Turbines%22,%22isChecked%22:true%7D%5D,%22selectedApplication%22:%22Super%20Resolution%22,%22selectedLayout%22:%22Single%20Map%22%7D)
> 
> ![image](https://user-images.githubusercontent.com/16768318/270134003-0621d424-9950-429b-a691-bb3e991e74de.png)

Hi Cesar! Thank you for bringing up these questions.

1) We trained on L1C data, not L2A. And the images were warped to webmercator to make alignment of multiple input images easier.

2) As for normalization, see the Sentinel-2 Images section of the main Satlas [repo](https://github.com/allenai/satlas/blob/main/Normalization.md#sentinel-2-images)
We used the L1C's 8-bit TCI image files for training these models.
