### ISSUE TITLE
Continuing the training where it stopped

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#20]
What do I have to change in the .yml file to continue where it left off?
Just give the path to the saved checkpoint file?
Do I also have to change something so that it continued logging in wandb?

**Comment by piperwolters** [comment]
You will need to add pretrain_network_g and pretrain_network_d arguments to the .yml file to load in weights for both the generator and the discriminator. If you want this to happen automatically, you can specify the --auto_resume flag in the training command.

To continue logging in wandb you'll need to edit the wandb.init() code in the repo. I haven't tested this, but you'd need to set resume=True.

**Comment by yunseok624** [comment]
Okay, thank you.
