### ISSUE TITLE
PROBA-V dataset question

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#21]
Hi,

My Proba-V dataset looks like the following:
- probav
   - train
      - RED
      - NIR
   - val
      - RED
      - NIR

And the yml file:
![image](https://github.com/allenai/satlas-super-resolution/assets/58263915/cb7a7ead-d3e1-4150-af61-09e0fe4277d4)

When I run the script I get such problem:
![image](https://github.com/allenai/satlas-super-resolution/assets/58263915/c67c9cd4-d9c7-4e8a-ae60-1e5c36727067)

**Comment by piperwolters** [comment]
First, are you using the probav_dataset.py file on the experiments branch? The experiments branch is a work in progress, that is why some of these files are not pushed to main.

In that file, I partially hardcoded the paths to train and val data. See the code [here](https://github.com/allenai/satlas-super-resolution/blob/experiments/ssr/data/probav_dataset.py#L33-L36). 
Let me know if that fixes this error, and if you find more. The PROBAV code is the least cleaned up of all the datasets.

**Comment by yunseok624** [comment]
Hi, forgot to close the issue.
I modified the code and successfully trained the model.
Thanks,

**Comment by piperwolters** [comment]
Awesome, glad to hear it.
