### ISSUE TITLE
Meaning behind the Training data's folder structure

### ISSUE THREAD

**Issue by VaasuDevanS** [allenai/satlas-super-resolution#22]
Thanks very much to the authors for making this work in the public domain. I have few questions regarding the folder structure.

Currently the folder structure for an image looks something like this:

```
├───naip
│   └───m_2608053_sw_17_060_20191203
│       └───36226_55652
│               rgb.png
│
└───sentinel2
    └───36226_55652
            b01.png
            b05.png
            b06.png
            b07.png
            b08.png
            b09.png
            b10.png
            b11.png
            b12.png
            tci.png
```

I would like to know the meaning behind the naip folder name. I think it's safe to assume `sw` stands for `south-west` and `20191203` is the date of NAIP image (`Dec 03, 2019`). What about `m_2608053`, `17_060` and `36226_55652`?

I am trying to locate the original NAIP image geographically for further analysis.

**Comment by piperwolters** [comment]
Of course. You are correct about the date and the quadrant indicator (ex. sw). 

m: This stands for "mosaic," indicating that the image is a part of a mosaic of tiles stitched together to cover a larger area.

2608053: This is a unique identifier for the specific tile. It typically includes information related to the location and quadrant of the imagery. For NAIP imagery, this number is often associated with the USGS (United States Geological Survey) quadrangle mapping system or a similar grid system used to segment and catalog the imagery.

17: This number represents the zoom level of the image. These NAIP images are on a web-mercator grid of zoom level 17 (2^17 x 2^17).

060: This part of the filename usually pertains to the version or series of the imagery. It could represent a batch number or a version number of the data release, helping users distinguish between different collections or updates of imagery.

**Comment by VaasuDevanS** [comment]
Thanks very much @piperwolters for the detailed clarification.
