### ISSUE TITLE
Question regarding logging in wandb

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#23]
Hello again,

Can you tell me in which part of the code losses are logged in wandb? And how it's logged. I understood almost the whole code, but not the part where all losses are logged.
I'm trying to change the code so that it also plots super-resolved images in wandb, so that it does not have to save the images in my computer every certain iteration. For some reason it takes a long time to save the validation results for whole small validation dataset, that's why I want to log the validation result in wandb to keep the track of the GAN (as you know it's hard to track the performance and result just based on losses).

Thank you in advance!

**Comment by piperwolters** [comment]
Of course! 

The wandb logger is initiated in the BasicSR code (which this code inherits). Here is the [init](https://github.com/XPixelGroup/BasicSR/blob/033cd6896d898fdd3dcda32e3102a792efa1b8f4/basicsr/utils/logger.py#L126), and metrics are logged in this[ area of code](https://github.com/XPixelGroup/BasicSR/blob/033cd6896d898fdd3dcda32e3102a792efa1b8f4/basicsr/models/sr_model.py#L249-L264).

It may be easier for you to add your own wandb code in this satlas-super-resolution code, as the BasicSR code can take a while to follow.

**Comment by yunseok624** [comment]
Understood!
thanks
