### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#25]
![image](https://github.com/allenai/satlas-super-resolution/assets/58263915/c250133d-e604-4f45-8c88-243b7440b13d)

Hi, can you tell me how long it took for you to train S2-NAIP on esrgan?
I'm started training with OSM discriminator & clip loss, however  I'm still in 200th iteration for 2.5.

**Comment by piperwolters** [comment]
How long does 1 train iteration take? You might want to validate less often or on a smaller set, so that takes less time. This seems quite slow.

I trained an esrgan, with 4 images as input, for 1million iterations, on S2-NAIP on 1 A6000 gpu in ~12 days.

**Comment by yunseok624** [comment]
It takes minimum 25min, but like you said I think it's the problem with validation.

For proba-v dataset, I validate every 100 iterations, but it trains very quickly and displays on wandb

**Comment by piperwolters** [comment]
Okay, I see. Try validating less during training (you could always run the evaluate script in a separate process while training is going), and see if speeds are ok.
