### ISSUE TITLE
How to Process Raw Sentinel-2 Data

### ISSUE THREAD

**Issue by YekunF** [allenai/satlas-super-resolution#28]
Hi Piper,
Thanks for arranging all the data descriptions and working pipelines. When I am going to infer new pics of Sentinel-2 Data, I am confused with the part of How to Process Raw Sentinel-2 Data since I did not find the **reproject_image** function in your repo. Are the following codes just pseudocode？
Appreciate your help,
Fang

**Comment by piperwolters** [comment]
Hi Fang, thanks for your interest in our work. 
That was mostly pseudocode, but you can find helpful reproject functions built into [rasterio](https://rasterio.readthedocs.io/en/latest/topics/reproject.html)
