### ISSUE TITLE
Using 4 bands (10m)

### ISSUE THREAD

**Issue by yunseok624** [allenai/satlas-super-resolution#32]
Hi!

Have you tried using 4 10m bands as input? Did you somehow preprocess the nir band cause I opened b08 band to visualise, however all values are 0.

**Comment by piperwolters** [comment]
Hi! Could you provide some example files where you observed this? Might be a data upload bug.

**Comment by yunseok624** [comment]
![b08](https://github.com/allenai/satlas-super-resolution/assets/58263915/f4d3ab25-c96e-40fc-8485-f2d6f42219e6)

Here's an example  of b08 band from small_val_set and when you visualize it, it's  pure black. It goes same for every band except tci.
It's same for every scene in small_val_set

**Comment by piperwolters** [comment]
Ah okay, I'm seeing the same thing in small_val_set but not any of the other sets. Must be an upload bug with just that set. Could you double check an image from a different set to make sure that is correct?

**Comment by yunseok624** [comment]
Hey, I checked all the files except train_urban and train_full, it has to big files that it takes to long to read, so couldn't check.
Others are fine

**Comment by piperwolters** [comment]
@yunseok624 Thanks for letting me know. I just uploaded a fixed small_val_set with actual data in all bands. Let me know if you see any issues.
