### ISSUE TITLE
Can't reproduce the results on new Sentinel-2 imagery (but on the test set, it works perfectly)

### ISSUE THREAD

**Issue by ettelephonne** [allenai/satlas-super-resolution#34]
First, thank you very much for this great work ! 
I used the 8 images model available on your github. It was easy to reproduce the results on the test dataset as shown here:
![image](https://github.com/allenai/satlas-super-resolution/assets/64080831/86c3c065-c221-440d-b9fd-9f952af0de87)
 
After this try, I downloaded from the GEE 8 Sentinel 2 16 bits images of Montreal (8 different dates). I converted these images to 8 bits png. I cut these images in patches (8 * 32 * 32 * 3). You can see exemples here:
![image](https://github.com/allenai/satlas-super-resolution/assets/64080831/3aeb74b6-e6c6-46b3-855d-b79c5c976418)
To me, these patches I made look exactly the same as those from the test sets:
![image](https://github.com/allenai/satlas-super-resolution/assets/64080831/f961b66a-268d-436f-9617-9dc6b02169a7)
But the result is not  as expected :
![image](https://github.com/allenai/satlas-super-resolution/assets/64080831/fd8feb2d-3bcc-4c71-89a9-218c7bde239f)
![image](https://github.com/allenai/satlas-super-resolution/assets/64080831/bfcf51f9-5890-40bf-bc7e-ca338884f403)
But I used the same model as for the test set... Do you have any clue to help me understand what did I miss ? Thank you very much for your time and your help.

**Comment by piperwolters** [comment]
Hi, thanks for your interest in our work!

To confirm, did you download Sentinel-2 L1C imagery, and use the TCI file provided by ESA? The range of these images should be 0-255 and be 8-bit. And did you reproject the imagery to Web-Mercator (pseudocode provided [here](https://github.com/allenai/satlas-super-resolution/tree/main#how-to-process-raw-sentinel-2-data)).

**Comment by tfriedel** [comment]
Had the same issue and it was the web mercator projection that was necessary. I guess it's important that the resolution matches the images used in training.
