### ISSUE TITLE
sample_net_g.pth and inference

### ISSUE THREAD

**Issue by martin416** [allenai/satlas-super-resolution#4]
Here are your questions :

1. Where can I download the file `experiments/sample_net_g.pth` mentioned in the `options/infer_example.yml` file?
2. How can I use the files generated by the method described in [this normalization guide for Sentinel-2 images](https://github.com/allenai/satlas/blob/main/Normalization.md#sentinel-2-images) to directly perform inference using an existing model? 
Thank you.

**Comment by martin416** [comment]
I don't want to do training; I want to perform inference directly from downloaded Sentinel-2 data in TIFF format using an existing model to see the results. 
Thank you

**Comment by piperwolters** [comment]
1. `experiments/sample_net_g.pth` is a placeholder. You will need to download weights and replace that with the path to the weights on your local system. There are model weights [here](https://github.com/allenai/satlas-super-resolution/tree/main#model-weights). These weights expect {2, 6, 12, 18} Sentinel-2 input images, respectively.
2. If you have your own Sentinel-2 data and want to use our inference script, you will need to reformat the data as described [here](https://github.com/allenai/satlas-super-resolution/tree/main#sentinel-2). 

An example command with our test data is [here](https://github.com/allenai/satlas-super-resolution/tree/main#inference).
