### ISSUE TITLE
The SR3 diffusion model code repo

### ISSUE THREAD

**Issue by patriksabol** [allenai/satlas-super-resolution#40]
Hello,

Do you plan to release the SR3 diffusion model code repository? If so, is there an estimated timeline or any update on its progress?

Thanks.

**Comment by piperwolters** [comment]
Hi, thanks for your issue.
The SR3 code repo is in a very research-codebase-state. I am happy to share it with you, but have not had the bandwidth to clean it up and thoroughly document it. A couple other users have been using it successfully, but again, it has not been cleaned up. Please email me at piperw@allenai.org and I can share the codebase.
