### ISSUE TITLE
Request Access to Web App for Displaying Super-Resolved Satellite Images

### ISSUE THREAD

**Issue by khlaifiabilel** [allenai/satlas-super-resolution#42]
Hello,

I have successfully generated super-resolved NIR bands and, as a result, I have been able to generate super-resolved indexes (e.g., NDVI). However, I am facing difficulties displaying these images, as I am not very experienced in web development.

I wanted to inquire if there is any access available to the web app used to display the super-resolved satellite images, which could help me visualize my results properly. Any guidance or support in integrating my data into the app would be highly appreciated.

Looking forward to your response.
PS : I am working n open sourcing the new results as they are based on this repo ressources.

Best regards,
[Khlaifiabilel](khlaifiabilel@icloud.com)

**Comment by piperwolters** [comment]
Hi, thanks for your interest in our work! Glad to hear you have successfully generated super-res NIR bands! 

Unfortunately, our web app is built with a lot of internal code... but the main functionality uses Mapbox GL JS ([https://docs.mapbox.com/mapbox-gl-js/guides/](https://docs.mapbox.com/mapbox-gl-js/guides/)). They seem to have a lot of good documentation, so hopefully that is an ok starting point.

Keep us updated on your progress!

**Comment by khlaifiabilel** [comment]
Greetings,

I didn't have the chance to fully appreciate the great work you've done on this project. However, I would love to collaborate with you on publishing the NIR super-resolved bands and the new pre-trained models.

Thank you very much!

**Comment by piperwolters** [comment]
Hi Khlaifiabilel! My team has reached out to your email to discuss next steps regarding publishing the NIR super-resolved bands and/or the pretrained models. Look forward to chatting.
