### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by oguzhannysr** [allenai/satlas-super-resolution#5]
Hello, I am trying to use this pre-trained model https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/satlas_explorer_datasets/super_resolution_models/esrgan_orig_12S2.pth but I am getting the following error.

![image](https://github.com/allenai/satlas-super-resolution/assets/53774968/f13455fe-9de1-4f1a-af9f-975f599ac3a3)

My input image is like this;

![image](https://github.com/allenai/satlas-super-resolution/assets/53774968/112e0ab6-6397-4c91-b8ab-b73995309806)

This is my yml file;
[infer_example.yml.txt](https://github.com/allenai/satlas-super-resolution/files/13811521/infer_example.yml.txt)

**Comment by piperwolters** [comment]
It looks like you need to change the argument, "num_in_ch", under "network_g" to 36 instead of 24. And make sure your rgb input contains 12 Sentinel-2 images in the format described in the README.

**Comment by oguzhannysr** [comment]
I didn't understand the 12 Sentinel-2 images part, and I couldn't see it in readmd either.

**Comment by piperwolters** [comment]
The required format of the input Sentinel-2 data is described [here](https://github.com/allenai/satlas-super-resolution?tab=readme-ov-file#sentinel-2).

If you have 12 Sentinel-2 images, with a shape of [12, h, w, 3], then you will need to reshape it to [12*h, w, 3] and save it as a png.

**Comment by oguzhannysr** [comment]
I understand, but can't I make an inference with a single image? Do I need to have at least 12 images?

**Comment by piperwolters** [comment]
Currently, we have just uploaded [model weights](https://github.com/allenai/satlas-super-resolution#model-weights) for models that expect 2, 6, 12, or 18 Sentinel-2 images. I can upload weights for a single-image model in the next few weeks.

**Comment by oguzhannysr** [comment]
"If you have 12 Sentinel-2 images, with a shape of [12, h, w, 3], then you will need to reshape it to [12*h, w, 3] and save it as a png." Is there any way or helpful code on how to do this?

**Comment by piperwolters** [comment]
Example code to do the reshaping:
```
import skimage.io
import numpy as np
arr = np.random.rand(12, 32, 32, 3)   # numpy array containing 12 Sentinel-2 images of size 32x32x3
reshape_arr = np.reshape(arr, (12*32, 32, 3))   # reshape this array so we can save it as a png
skimage.io.imsave('testing.png', reshape_arr)   # save this array as a png
```

The Sentinel-2 time series saved in this format will look like the following example image:
![tci](https://github.com/allenai/satlas-super-resolution/assets/46272042/8d1b7b50-475a-4f52-8500-a057be531f20)

**Comment by oguzhannysr** [comment]
Thank you for your efforts. The shape of the 2 images I want to test is 2000,2000. First of all, do I need to divide these images into 32*32 pieces? I would be happy if you could help me, I have little experience.

**Comment by oguzhannysr** [comment]
Thank you, I solved the problem, setting n_lr_images: 2 solved it. But while running the infer_grid.py file, I got an error in a file towards the end of the files.

![image](https://github.com/allenai/satlas-super-resolution/assets/53774968/3fe5ba2c-a3f1-4865-acc6-cbd9bc987589)

**Comment by oguzhannysr** [comment]
I solved this too, the only problem remains the stitching process. I'm getting an error when combining these.

**Comment by piperwolters** [comment]
Glad to hear you solved those issues. To be clear, are you dividing your 2000x2000 image into 32x32 chunks before running inference?

If so - the infer_grid.py file has a few hard-coded values that you will likely need to change in [this](https://github.com/allenai/satlas-super-resolution/blob/main/ssr/infer_grid.py#L67) section of code.
By default, it is expecting to stitch a 16x16 grid of both 32x32 Sentinel-2 images and 128x128 Super-Resolved images. If you have somehow divided your 2000x2000 image into overlapping 32x32 chunks, then this stitch code will not work since it expects non-overlapping, perfectly aligned chunks. If you reshaped your 2000x2000 image to be divisible by 32 before chunking it into 32x32 chunks, then you may just need to change the hard-coded input args to the `stitch()` function.

Alternatively, you could try dividing your 2000x2000 image into 125x125 chunks (2000 / 16 = 125). Then run the inference script on that. The stitching should work then.
That would not perfectly match how the models were trained, but I've found small scale differences to be ok.

**Comment by oguzhannysr** [comment]
Yes, first of all, I combine my two sentinel-2 images as a time series as you sent, divide them into 32*32 pieces and run the model in the infer_grid.py file. I made some changes and got 128*128 sr images. In some places the code did not work, so I assigned black pixels to them. I will show you these results below.

But the problem is not the merging of these 128*128 images, but the georeferencing. I wrote a code for this but I need to improve it. I haven't decided what to do for this yet. Can you help me with this? How can I do Affine transformations

**code for georeferencing:** 

[STICH.py.txt](https://github.com/allenai/satlas-super-resolution/files/13834070/STICH.py.txt)

**result stiched image**

https://drive.google.com/file/d/1cSQEPYYX08BELVyZYgrcpAcpPxyyfOui/view?usp=sharing
**one of the two sentine**
https://drive.google.com/file/d/1QKuEr2YeZDvbo0ovDUBO8MxWiQ8pS6W3/view?usp=sharing

**Comment by oguzhannysr** [comment]
@piperwolters

**Comment by piperwolters** [comment]
The input Sentinel-2 image and stitched output looks good aside from the black chunks (do you have the error / reason why those did not work)?

**Comment by oguzhannysr** [comment]
The reason for the black pixels is that when dividing the image into 32*32 pieces, some parts are not 32*32 in size.
I'm also looking forward to your help regarding georeferencing.

**Comment by favyen2** [comment]
1. Not 32x32 in size -- you can pad the input image to be a multiple of 32 in both dimensions. Then crop the resulting output to 4 times the original width and height (before padding).
2. Georeferencing -- it makes sense to copy the transform and CRS from the same GeoTIFF that you are using for the input. But you need to multiply the resolution by 4. With rasterio it should have Affine object like this:

```
Affine(x_off, x_res, 0, y_off, 0, y_res)
```

So you can divide the x_res and y_res by 4 (they should be like meters/pixel, input is 10 m/pixel and output is 2.5 m/pixel.
