### ISSUE TITLE
Inference result

### ISSUE THREAD

**Issue by xuliu-cyber** [allenai/satlas-super-resolution#6]
Hello, I use the esrgan_orig_2S2 pretrained model to infer grid, and I copy one low resolution image
![Anhui_Chaohu_2020_Spring_S2_RGB](https://github.com/allenai/satlas-super-resolution/assets/61044387/f5ffe96d-e378-419e-9114-fdadbdae7d94)
I got the high resolution image:
![QQ截图20240113172531](https://github.com/allenai/satlas-super-resolution/assets/61044387/b9dea049-8ef6-4bb5-af1d-6ceb0c9d7453)
I have two questions: 1 Can color differences between different image grids be eliminated?
2 Why are there so many mosaics?
I hope to receive your answer! Thank you!

**Comment by piperwolters** [comment]
Hi there, thank you for your issue.

It looks like a bug where the pixel values aren't being clamped between 0-1 before being converted to an image and saved - I have pushed a fix [here](https://github.com/allenai/satlas-super-resolution/commit/1a78390260ef6be1c29f67d4d759e19f3adae8c9).  Let me know if this is fixes the weird color artifacts.

As far as differences between the grid cells, we have tried some blending techniques but haven't found any methods that work well. Most of them over-average and cause a blurriness at the borders. We'll keep working on this.

Also, are you using L1C or L2A Sentinel-2 images? The pretrained weights all used L1C imagery.

**Comment by xuliu-cyber** [comment]
Thanks, The clamp operation is useful!
And I wonder how much the number of the input imgs effects the result？

**Comment by piperwolters** [comment]
I found that increasing the number of input images has a large effect in performance until you get to ~8-10 images, and after that the benefit is not as large.

**Comment by nabeelraza-7** [comment]
Can you share where the link or path of the pre-trained weights? I want to use it for a similar case.
