### ISSUE TITLE
Extracting the train_urban_set

### ISSUE THREAD

**Issue by SarmadNR** [allenai/satlas-super-resolution#9]
Hi, this might be obvious but I am struggling to extract these files. The train_urban_set contains three file 

1. train_urban_set.z01
2. train_urban_set.z02
3. train_urban_set.z03

How to extract these? I have tried unzip / tar.

Thanks.

**Comment by piperwolters** [comment]
What error are you getting when running unzip?

**Comment by SarmadNR** [comment]
Hi , Thank you for your reply.

https://linuxconfig.org/how-to-split-zip-archive-into-multiple-blocks-of-a-specific-size

I am following the above guide and according to it I need a **.zip** file that does not exist. Where can I find this .zip file?

On my linux machine I ran the following command:

**unzip train_urban_set.z01 train_urban_set.z02 train_urban_set.z03**

I get the following error.

Archive:  train_urban_set.z01
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of train_urban_set.z01 or
        train_urban_set.z01.zip, and cannot find train_urban_set.z01.ZIP, period.

**Comment by piperwolters** [comment]
Ah okay, I'll re-upload these with the .zip file too. In the mean time, if you are able to download [this](https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/satlas_explorer_datasets/super_resolution_2023-12-08.tar), it contains the train/val/test data all in one and should not have this issue.

**Comment by SarmadNR** [comment]
Thanks for this link. However, It seems like the same link that is already provided in the repo. It contains 128 x 128 NAIP images. Whereas I am interested in 512 x 512 present in it. I will download it anyway to double-check.

Looking forward to the .zip file.

**Comment by piperwolters** [comment]
Oh, I'm sorry but we only provide the downsampled NAIP images of shape 128x128. We trained most models to upsample by a factor of 4, since semantic accuracy is already a challenge with 4x upsampling.

**Comment by SarmadNR** [comment]
Okay, thanks for the information!
